learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin


# 包含模块，模块定义了可在管理网站中请求的所有 url
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),
    
    ]

learning_logs/urls.py
'''定义 learning_logs 的URL模式'''

from django.conf.urls import url

from . import views

#app_name = 'learning_logs'
urlpatterns = [
    # 主页
    # 调用 views.index,指定其名称为 index, 方便其他调用
    url(r'^$',views.index, name='index'),
    
    # 显示所有的主题
    url(r'^topics/$',views.topics,name='topics'),
    # 特定主题的详细页面
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    # 用于添加新主题的网页
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    # 用于添加新条目
    url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
    # 用于编辑既有条目
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),
    ]

users/urls.py
'''为应用程序 users 定义 URL 模式'''

from django.conf.urls import url
from django.contrib.auth.views import login # 默认视图

from . import views

urlpatterns = [
    # 登录页面
    url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    # 注册页面
    url(r'^register/$',views.register,name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)  # 预留200
    date_added = models.DateTimeField(auto_now_add=True) # 自动记录当前时间
    owner = models.ForeignKey(User)
    
    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text

class Entry(models.Model):
    '''学到的某个主题的具体知识'''
    # 取得主题创建时，分配的键（ID）
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    # 存储用于管理模型的额外信息：设置特殊属性，用 Entries 表示多个条目
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        if len(self.text) > 50:
            return self.text[:50] + '...'
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    # 根据哪个模型创建表单，以及表单只包含text，不为字段生成标签
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        # 覆盖 django 默认的小部件:制定 text 输入的小部件宽度设置为 80，而不是40默认
        widgets = {'text':forms.Textarea(attrs={'cols':80})}
        

learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required



def index(request):
    '''学习笔记主页'''
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    '''显示所有的主题'''
    # 按照属性 date_added 对它们进行排序
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)

@login_required   
def topic(request,topic_id):
    # 单个主题与其所有的条目
    topic = Topic.objects.get(id=topic_id) # topic_id 为正则表达式捕获的值
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added') # - 表示降序
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

@login_required    
def new_topic(request):
    '''添加新主题'''
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form  = TopicForm()
    else:
        # POST提交的数据，对数据处理
        form = TopicForm(request.POST)
        # 判断数据是否有效
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # 重定向到网页 topics,reverse,根据指定的URL模型确定URL
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required    
def new_entry(request,topic_id):
    '''在特定的主题中添加新条目'''
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False) # 不保存在数据库
            new_entry.topic = topic # 把 topic 赋给
            new_entry.save() #保存数据库
            return HttpResponseRedirect(reverse('learning_logs:topic',
                    args=[topic.id]))
                    
    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)
    
@login_required
def edit_entry(request,entry_id):
    '''编辑既有条目'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntryForm(instance=entry) # 使用既有条目填充
    
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                args=[topic.id]))
    
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    '''注册新用户'''
    if request.method !="POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登陆，在重定向到主页，注册时输入了两次密码，返回通过身份验证的对象
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Learning log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  
  <body>
    
    <!-- static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
              Learning Log</a>
        </div>
      
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
          </ul>
        
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello,{{ user.user.name }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
           {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
    
    <div class="container">
    
      <div  class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
      
    </div><!-- /container -->
    
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit entry:</h2>
{% endblock header %}

{% block content %}

  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
  
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='POST'
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changges</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}  <!--继承自 base.html-->

{% block header %}
  <div class='jumbotron'>
    <h1>Track your learning.</h1>
  </div>
{% endblock header %}  

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log,and list the topics you're learning about.
  </h2>
  <h2>
    Whenever you learn something new about a topic,make an entry summarizing
    what you've learned.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new entry:</h2>
{% endblock header %} 

{% block content %}

  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
  
  <!-- 将表单 Post 到 new_entry-->
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'
        class='form'>
        
    {% csrf_token %} <!-- 防止跨站请求伪造 -->
    {% bootstrap_form form %}  <!-- 显示表单 -->
    
    {% buttons %}
    <button name='submit' class='btn btn-primary'>add entry</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
  
  <!-- 将表单 Post 到 new_topic,调用 new_topic 完成重定向 -->
  <form action="{% url 'learning_logs:new_topic' %}" method='post' 
        class='form'>
    {% csrf_token %} <!-- 防止跨站请求伪造 -->
    {% bootstrap_form form %}   <!-- 显示表单 -->
    {% buttons %}
    <button name='submit' class="btn btn-primary">add topic</button>
    <!-- 提交按钮 -->
    {% endbuttons %}
  </form>
  
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block header %}
  <h2>{{ topic }}</h2>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>
{% endblock header %}
 
{% block content %}
  
  
  {% for entry in entries %}
    <div class='panel panel-default'>
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d,Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!--panel -->
  {% empty %}
      There are no entries for this topic yet.
  {% endfor %}


{% endblock content %}
    
  

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}
  
  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li> <!-- 模板中打印变量使用双花括号 -->
    {% empty %} <!-- 告诉列表为空时该怎么办 -->
      <li>No topics have been added yet.</li>
    {% endfor %} <!-- 指出for循环结束位置 -->
  </ul>
  
  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
  
{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
  
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name='submit' class='btn btn-primary'>log in</button>
    {% endbuttons %}  
    
    <input type='hidden' name='next' value="{%url 'learning_logs:index' %}"/>
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register your account.</h2>
{% endblock header %}

{% block content %}
  
  <form method='post' action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name='submit' class='btn btn-primary'>Register</button>
    {% endbuttons %} 
    
    <input type='hidden' name='next' value="{% url 'learning_logs:index' %}" />
  </form>
  
{% endblock content %}